name: Deploy constic

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build

      - name: Upload build folder via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: 22
          source: "build/*"
          target: "/public_html/materiales"
